import type { Config } from 'tailwindcss';

// Tokens transcribed from stitch_screens/design_system.md ("Eternal Union").
const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fef8f9',
        'surface-dim': '#ded9da',
        'surface-bright': '#fef8f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8f2f3',
        'surface-container': '#f2eced',
        'surface-container-high': '#ece7e8',
        'surface-container-highest': '#e7e1e2',
        'on-surface': '#1d1b1c',
        'on-surface-variant': '#514346',
        'inverse-surface': '#323031',
        'inverse-on-surface': '#f5eff0',
        outline: '#847376',
        'outline-variant': '#d6c2c5',
        'surface-tint': '#894c5c',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#380a1a',
        'on-primary-container': '#b47081',
        'inverse-primary': '#feb1c4',
        secondary: '#b02559',
        'on-secondary': '#ffffff',
        'secondary-container': '#fd6293',
        'on-secondary-container': '#66002d',
        tertiary: '#735c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#cba72f',
        'on-tertiary-container': '#4e3d00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffd9e0',
        'primary-fixed-dim': '#feb1c4',
        'on-primary-fixed': '#380a1a',
        'on-primary-fixed-variant': '#6d3545',
        'secondary-fixed': '#ffd9e0',
        'secondary-fixed-dim': '#ffb1c3',
        'on-secondary-fixed': '#3f0019',
        'on-secondary-fixed-variant': '#8f0142',
        'tertiary-fixed': '#ffe088',
        'tertiary-fixed-dim': '#e9c349',
        'on-tertiary-fixed': '#241a00',
        'on-tertiary-fixed-variant': '#574500',
        background: '#fef8f9',
        'on-background': '#1d1b1c',
        'surface-variant': '#e7e1e2',
      },
      fontFamily: {
        heading: ['var(--font-caslon)', 'Libre Caslon Text', 'serif'],
        body: ['var(--font-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.3', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'section-gap': '120px',
        'section-gap-mobile': '64px',
      },
      maxWidth: {
        container: '1200px',
      },
      boxShadow: {
        card: '0 4px 20px rgba(45, 3, 18, 0.05)',
        float: '0 8px 30px rgba(45, 3, 18, 0.08)',
      },
    },
  },
  plugins: [],
};

export default config;
